"""Update players table

Revision ID: 83f624949d7b
Revises: 
Create Date: 2024-12-08 12:58:01.381176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f624949d7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teams_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_players_first_name', table_name='players')
    op.drop_index('ix_players_id', table_name='players')
    op.drop_index('ix_players_last_name', table_name='players')
    op.drop_index('ix_players_team', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_divisions_id', table_name='divisions')
    op.drop_table('divisions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('divisions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='divisions_pkey'),
    sa.UniqueConstraint('name', name='divisions_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_divisions_id', 'divisions', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ELO_points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='players_pkey')
    )
    op.create_index('ix_players_team', 'players', ['team'], unique=False)
    op.create_index('ix_players_last_name', 'players', ['last_name'], unique=False)
    op.create_index('ix_players_id', 'players', ['id'], unique=False)
    op.create_index('ix_players_first_name', 'players', ['first_name'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('division_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name='teams_division_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    sa.UniqueConstraint('number', name='teams_number_key')
    )
    op.create_index('ix_teams_id', 'teams', ['id'], unique=False)
    # ### end Alembic commands ###
